import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import HeaderPage from './components/HeaderPage'
import FooterPage from './components/FooterPage'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Memmingen-Info',
  description: 'Generated by create next app', //??
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <HeaderPage />
        <main className="container">
          {children}
        </main>
        <FooterPage />
      </body>
    </html>
  )
}
